version: '3.8'

services:
  web:
    build: .
    restart: always
    env_file: .env
    volumes:
      - ./data:/app/data
      - ./static:/app/static
      - ./media:/app/media
      - ./score/static:/app/score/static
    ports:
      - "${PORT:-8000}:8000"
    environment:
      - DJANGO_SUPERUSER_USERNAME=${ADMIN_USERNAME:-admin}
      - DJANGO_SUPERUSER_PASSWORD=${ADMIN_PASSWORD:-admin}
      - DJANGO_SUPERUSER_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      - DATABASE_PATH=${DATABASE_PATH:-/app/data/db.sqlite3}
      - DEBUG=False  # 強制設定為 False，不使用環境變數
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - SKIP_IMPORT=True  # 跳過 Excel 資料匯入步驟
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
