# Generated by Django 5.2.1 on 2025-05-14 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "admit_number",
                    models.CharField(
                        max_length=10,
                        primary_key=True,
                        serialize=False,
                        verbose_name="准考證號",
                    ),
                ),
                (
                    "id_last_4_digits",
                    models.CharField(max_length=4, verbose_name="身份證末4碼"),
                ),
                ("name", models.CharField(max_length=20, verbose_name="姓名")),
            ],
            options={
                "verbose_name": "考生資料",
                "verbose_name_plural": "考生資料",
            },
        ),
        migrations.CreateModel(
            name="FoodManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("food_identification", models.FloatField(verbose_name="食材辨識")),
                (
                    "utensil_identification",
                    models.FloatField(verbose_name="餐飲器具辨識"),
                ),
                ("total_score", models.FloatField(verbose_name="術科總成績")),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_score",
                        to="score.student",
                        verbose_name="考生",
                    ),
                ),
            ],
            options={
                "verbose_name": "餐飲管理科成績",
                "verbose_name_plural": "餐飲管理科成績",
            },
        ),
        migrations.CreateModel(
            name="FashionDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("basic_sewing", models.FloatField(verbose_name="基礎設計手縫")),
                ("creative_drawing", models.FloatField(verbose_name="創意繪圖")),
                ("total_score", models.FloatField(verbose_name="術科總成績")),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fashion_score",
                        to="score.student",
                        verbose_name="考生",
                    ),
                ),
            ],
            options={
                "verbose_name": "流行服飾科成績",
                "verbose_name_plural": "流行服飾科成績",
            },
        ),
        migrations.CreateModel(
            name="StylingDesign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("basic_sewing", models.FloatField(verbose_name="基礎設計手縫")),
                ("color_drawing", models.FloatField(verbose_name="整體造型色彩繪圖")),
                ("total_score", models.FloatField(verbose_name="術科總成績")),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="styling_score",
                        to="score.student",
                        verbose_name="考生",
                    ),
                ),
            ],
            options={
                "verbose_name": "整體造型特色班成績",
                "verbose_name_plural": "整體造型特色班成績",
            },
        ),
    ]
